export const SET_LOCATION = 'SET_LOCATION'
export const FETCH_FORECASTS_REQUEST = 'FETCH_FORECASTS_REQUEST'
export const FETCH_FORECASTS_FAILURE = 'FETCH_FORECASTS_FAILURE'
export const FETCH_FORECASTS_SUCCESS = 'FETCH_FORECASTS_SUCCESS'
